import {
  simpleAngular,
  simpleC,
  simpleDocker,
  simpleDotnet,
  simpleFastapi,
  simpleGit,
  simpleGooglecloud,
  simpleJavascript,
  simpleJenkins,
  simpleJquery,
  simpleJupyter,
  simpleMongodb,
  simpleMysql,
  simpleNestjs,
  simpleNextdotjs,
  simpleNodedotjs,
  simpleNumpy,
  simplePandas,
  simplePostgresql,
  simplePython,
  simpleReact,
  simpleSubversion,
  simpleTypescript,
} from '@ng-icons/simple-icons';

export const TECH_ICONS = {
  simpleReact,
  simpleAngular,
  simpleNextdotjs,
  simpleNestjs,
  simplePython,
  simpleFastapi,
  simpleGooglecloud,
  simpleMongodb,
  simpleGit,
  simpleTypescript,
  simpleNodedotjs,
  simplePostgresql,
  simpleDocker,
  simpleDotnet,
  simpleJavascript,
  simpleJquery,
  simpleC,
  simpleMysql,
  simpleJenkins,
  simpleSubversion,
  simpleNumpy,
  simplePandas,
  simpleJupyter,
};

export const TECH_ICON_MAP = {
  react: 'simpleReact',
  angular: 'simpleAngular',
  'next.js': 'simpleNextdotjs',
  nestjs: 'simpleNestjs',
  python: 'simplePython',
  fastapi: 'simpleFastapi',
  gcloud: 'simpleGooglecloud',
  mongodb: 'simpleMongodb',
  git: 'simpleGit',
  typescript: 'simpleTypescript',
  'node.js': 'simpleNodedotjs',
  postgresql: 'simplePostgresql',
  docker: 'simpleDocker',
  '.net': 'simpleDotnet',
  javascript: 'simpleJavascript',
  jquery: 'simpleJquery',
  'c#': 'simpleC',
  'sql server': 'simpleMysql',
  jenkins: 'simpleJenkins',
  svn: 'simpleSubversion',
  numpy: 'simpleNumpy',
  pandas: 'simplePandas',
  'jupyter notebooks': 'simpleJupyter',
};
